import { provideIcons } from '@ng-icons/core';
import {
  lucideArrowUp,
  lucideBox,
  lucideChevronRight,
  lucideCode,
  lucideDatabase,
  lucideGithub,
  lucideLinkedin,
  lucideMail,
  lucideMapPin,
  lucideMenu,
  lucideSend,
  lucideSmartphone,
  lucideSquareCode,
  lucideTerminal,
  lucideTrendingUp,
  lucideUsers,
  lucideX,
} from '@ng-icons/lucide';

export const portfolioIconProviders = provideIcons({
  'lucide-terminal': lucideTerminal,
  'lucide-menu': lucideMenu,
  'lucide-x': lucideX,
  'lucide-chevron-right': lucideChevronRight,
  'lucide-github': lucideGithub,
  'lucide-linkedin': lucideLinkedin,
  'lucide-mail': lucideMail,
  'lucide-arrow-up': lucideArrowUp,
  'lucide-square-code': lucideSquareCode,
  'lucide-database': lucideDatabase,
  'lucide-smartphone': lucideSmartphone,
  'lucide-box': lucideBox,
  'lucide-trending-up': lucideTrendingUp,
  'lucide-users': lucideUsers,
  'lucide-send': lucideSend,
  'lucide-map-pin': lucideMapPin,
  'lucide-code': lucideCode,
});
