import { provideIcons } from '@ng-icons/core';
import {
  lucideArrowUp,
  lucideAward,
  lucideBot,
  lucideBox,
  lucideChevronRight,
  lucideCode,
  lucideDatabase,
  lucideExternalLink,
  lucideFolderGit2,
  lucideGithub,
  lucideLinkedin,
  lucideLock,
  lucideMail,
  lucideMapPin,
  lucideMenu,
  lucideSend,
  lucideServer,
  lucideSmartphone,
  lucideSparkles,
  lucideSquareCode,
  lucideTerminal,
  lucideTrendingUp,
  lucideUsers,
  lucideWalletCards,
  lucideWorkflow,
  lucideX,
} from '@ng-icons/lucide';

export const portfolioIconProviders = provideIcons({
  'lucide-terminal': lucideTerminal,
  'lucide-menu': lucideMenu,
  'lucide-x': lucideX,
  'lucide-chevron-right': lucideChevronRight,
  'lucide-github': lucideGithub,
  'lucide-linkedin': lucideLinkedin,
  'lucide-mail': lucideMail,
  'lucide-arrow-up': lucideArrowUp,
  'lucide-square-code': lucideSquareCode,
  'lucide-database': lucideDatabase,
  'lucide-smartphone': lucideSmartphone,
  'lucide-box': lucideBox,
  'lucide-trending-up': lucideTrendingUp,
  'lucide-users': lucideUsers,
  'lucide-send': lucideSend,
  'lucide-server': lucideServer,
  'lucide-map-pin': lucideMapPin,
  'lucide-code': lucideCode,
  'lucide-lock': lucideLock,
  'lucide-external-link': lucideExternalLink,
  'lucide-award': lucideAward,
  'lucide-folder-git-2': lucideFolderGit2,
  'lucide-workflow': lucideWorkflow,
  'lucide-bot': lucideBot,
  'lucide-sparkles': lucideSparkles,
  'lucide-wallet-cards': lucideWalletCards,
});
